export const filterValues: any = {
  listing_type: ['buy', 'rent'],
  sort: ['Relevancy',
    'Bedroom low-high',
    'Bedroom high-low',
    'Price low-high',
    'Price high-low',
    'Newest',
    'Oldest'],
  beds: [1, 2, 4, 5],
  propertyType: ['flat', 'house', 'all'],
  priceMin: 0,
  priceMax: 99999999,
  bathrooms: [1, 2, 3, 4],
};
