export const LANG_FR_NAME = 'FR';

export const LANG_FR_TRANS = {
  'Property cross': 'Croix de propriété',
  'Use the form below to search for houses to buy.You can search by place-name, postcode, or click \'My location\', to search in your current location!' : 'Utilisez le formulaire ci-dessous pour rechercher des maisons à acheter. Vous pouvez rechercher par nom-lieu, code postal, ou cliquez sur \'Mon emplacement\'pour rechercher dans votre emplacement actuel!',
  'Latest search' : 'Dernière recherche',
  'Home' : 'Accueil',
  'Favourite' : 'favori',
  'For buy': 'acheter',
  'For rent': 'location',
  'Relevancy': 'Pertinence',
  'Bedroom (low to high)' : 'Chambre à coucher (faible à élevé)',
  'Bedroom (high to low)' : 'Chambre à coucher (haut à bas)',
  'Price (low to high)' : 'Prix (faible à élevé)',
  'Price (high to low)' : 'Prix (élevé à bas)',
  'Newest' : 'Les plus récents',
  'Oldest' : 'Le plus ancien',
  'Studio' : 'Studio',
  'Beds' : 'Des lits',
  'Property type' : 'Type de propriété\n',
  'All' : 'Tout',
  'Flat' : 'Appartement',
  'House' : 'Maison',
  'Bathrooms' : 'Salles de bains',
  'Founded' : 'Fondé',
  'Price' : 'Prix',
  'flat' : 'appartement',
  'rent' : 'location',
  'for' : 'para',
  'Baths' : 'Thermes',
  'Range' : 'Gamme',
  'First' : 'Premier',
  'Enter city' : 'Entrez la ville',
  'Last' : 'Dernier',
  'Brazil' : 'Brésil',
  'Germany' : 'Allemagne',
  'Spain' : 'Espagne',
  'France' : 'France',
  'India' : 'Inde',
  'Italy' : 'Italie',
  'Mexico' : 'Mexique',
  'UK' : 'Royaume-Uni'
};
