export const LANG_DE_NAME = 'DE';

export const LANG_DE_TRANS = {
  'Property cross': 'Eigentum Kreuz',
  'Use the form below to search for houses to buy.You can search by place-name, postcode, or click \'My location\', to search in your current location!' : 'Verwenden Sie das untenstehende Formular, um nach Häusern zu suchen. Sie können nach Ortsnamen, Postleitzahl suchen oder auf \' Mein Standort \' klicken, um in Ihrem aktuellen Standort zu suchen!',
  'Latest search' : 'Neueste Suche',
  'Home' : 'Zuhause',
  'Favourite' : 'Favorit',
  'For buy': 'kaufen',
  'For rent': 'Miete',
  'Relevancy': 'Relevanz',
  'Bedroom (low to high)' : 'Schlafzimmer (niedrig bis hoch)',
  'Bedroom (high to low)' : 'Schlafzimmer (absteigend)',
  'Price (low to high)' : 'Preis (niedrig bis hoch)',
  'Price (high to low)' : 'Preis (absteigend)',
  'Newest' : 'Neueste',
  'Oldest' : 'Älteste',
  'Studio' : 'Studio',
  'Beds' : 'Betten',
  'Property type' : 'Art der Immobilie\ne',
  'All' : 'Alle',
  'Flat' : 'Wohnung',
  'House' : 'Haus',
  'Bathrooms' : 'Badezimmer',
  'Founded' : 'Gegründet',
  'Price' : 'Preis',
  'flat' : 'Wohnung',
  'rent' : 'Miete',
  'for' : 'zum',
  'Baths' : 'Bad',
  'Range' : 'Angebot',
  'First' : 'Zuerst',
  'Enter city' : 'Stadt betreten',
  'Last' : 'Letzte',
  'Brazil' : 'Brasilien',
  'Germany' : 'Deutschland',
  'Spain' : 'Spanien',
  'France' : 'Frankreich',
  'India' : 'Indien',
  'Italy' : 'Italien',
  'Mexico' : 'Mexiko',
  'UK' : 'Vereinigtes Königreich'
};
