export const LANG_BR_NAME = 'BR';

export const LANG_BR_TRANS = {
  'Property cross': 'Cruz de propriedade',
  'Use the form below to search for houses to buy.You can search by place-name, postcode, or click \'My location\', to search in your current location!' : 'Use o formulário abaixo para procurar casas para comprar. Você pode pesquisar por nome-local, código postal ou clique em "Minha localização" para pesquisar em sua localização atual.',
  'Latest search' : 'Pesquisa mais recente',
  'Home' : 'Casa',
  'Favourite' : 'Favorito',
  'For buy': 'Comprar',
  'For rent': 'Alugar',
  'Relevancy': 'Relevância',
  'Bedroom (low to high)' : 'Quarto (baixo para alto)',
  'Bedroom (high to low)' : 'Quarto (alto a baixo)',
  'Price (low to high)' : 'Preço (baixo para alto)',
  'Price (high to low)' : 'Preço (alto a baixo)',
  'Newest' : 'O mais novo',
  'Oldest' : 'Mais antigos',
  'Studio' : 'Estúdio',
  'Beds' : 'Camas',
  'Property type' : 'Tipo de Propriedade',
  'All' : 'Todos',
  'Flat' : 'Plano',
  'House' : 'casa',
  'Bathrooms' : 'Banheiros',
  'Founded' : 'Fundado',
  'Price' : 'Preço',
  'flat' : 'plano',
  'rent' : 'aluguel',
  'for' : 'para',
  'Baths' : 'Banhos',
  'Range' : 'Alcance',
  'First' : 'Primeiro',
  'Enter city' : 'Insira a cidade',
  'Last' : 'Último',
  'Brazil' : 'Brasil',
  'Germany' : 'Alemanha',
  'Spain' : 'Espanha',
  'France' : 'França',
  'India' : 'Índia',
  'Italy' : 'Itália',
  'Mexico' : 'México',
  'UK' : 'Reino Unido'
};
